ALTER TABLE "Activity" ALTER COLUMN "addressId" DROP NOT NULL;
ALTER TABLE "Activity" ALTER COLUMN "addressId" DROP DEFAULT;
UPDATE "Activity" SET "addressId" = NULL WHERE "addressId" = 0;

ALTER TABLE "Activity" ADD CONSTRAINT "Activity_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "Address"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Schedule" ADD COLUMN     "name" VARCHAR(255);
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Activity" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Exemplar" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Schedule" ALTER COLUMN "name" SET DATA TYPE TEXT;
